DROP TABLE IF EXISTS tbl_user;
CREATE TABLE tbl_user(
	username VARCHAR(50) NOT NULL PRIMARY KEY,
	salt TINYBLOB,
	HASH TINYBLOB,
	email VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	surname VARCHAR(50) NOT NULL,
	user_type ENUM('STUDENTE', 'MAESTRO') NOT NULL
);
SELECT * FROM tbl_user;